### ISSUE TITLE
Interactions param/remap js parsing

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tools#10]
Might be good to save a javascript module which has a function that does this parsing (so people don't have to keep copy/pasting).

@jihoonl did you have plans/ideas on creating a place for storing a library of these things?

I noticed the listener example I pulled from roslibjs was using links to a file server serving them.

Is linking them to raw github url's considered bad?

**Comment by jihoonl** [comment]
Using raw github url could be the temporal solution until we setup CDN(content delivery network).
CDN is used to serve javascript libraries in many places. JQuery, Robot Web tool, etc uses it.

http://en.wikipedia.org/wiki/Content_delivery_network

**Comment by stonier** [comment]
There's no equivalent of pypi (python), or maven central (java)?

Does Robot Web Tools use a paid CDN or a free one?

**Comment by jihoonl** [comment]
Forwarding the question to https://github.com/robotics-in-concert/rocon_tools/issues/12
