### ISSUE TITLE
`wait_for_service` should support indefinite waiting

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#103]
Just like the original implementation: http://wiki.ros.org/rospy/Overview/Services#Service_proxies

Currently providing `rospy.Duration(0)` or just no argument does not work.

**Comment by stonier** [comment]
It's a different api, but gives the one-shot functionality as well as the indefinite blocking and easier calling (I hate having to catch so many exceptions in python).

**Comment by stonier** [comment]
Cherry-picked across to the gopher/develop branches as well.

**Comment by bit-pirate** [comment]
Cool. Thanks!
