### ISSUE TITLE
Javascript questions

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tools#12]
- **Best Practices**
  - Use a semi-colon at the end of a line or not (both seem to work)?
  - Indent of 2 or 4 spaces?
  - How to comment a function (like doxygen or python)?
- **Serving**
  - How to serve development javascript?
  - How to serve production javascript?
  - Can scripts call other scripts?

I'm sure more will be coming :neckbeard:

**Comment by stonier** [comment]
**Development Javascript Serving**

Hosting from `raw.github.com` doesn't work, github serves it as `text/plain` and not `text/javascript`. Google chrome will throw an error if you try this. There are proxies for this - `rawgithub.com` and `raw.githack.com` ([githack](https://raw.githack.com/)). But these are for development only - don't do these for high usage. And they may very easily disappear.

**Comment by stonier** [comment]
**Production Serving**

Github recommends doing this from github pages (not raw github).

**Comment by jihoonl** [comment]
> - Use a semi-colon at the end of a line or not (both seem to work)?
> - Indent of 2 or 4 spaces?
> - How to comment a function (like doxygen or python)?

http://wiki.ros.org/JavaScriptStyleGuide

> - How to serve development javascript?

Like you said, githack may work. We can easily setup to use our server to serve js files as well.

> - How to serve production javascript?

Most of javascript libraries are served using CDN.  Robot Web Tool uses Amazon S3 as CDN to serve javascript modules as well as collada model. Using CDN is very common in client side javascript module serving.

Also server side javascript(node.js) uses npm. However, there is no central repo like pip or maven for browser side js libraries. Central repository does not make sense for browser js libs as well. These libs are too frequently accessed to be centralised.

> - Can scripts call other scripts?

Yes. Javascript framework like backbone, dojo, angular helps to manipulate javascript modules. However, it is not easy at all by the sake of javascript. There is nothing like "include" or "import".

**Comment by stonier** [comment]
> http://wiki.ros.org/JavaScriptStyleGuide

Where do these motivations come from? e.g. the c++ motivations come from alot (not all) of the ideas in the google style guide. Python largely comes from pep8.

> Like you said, githack may work. We can easily setup to use our server to serve js files as well.

I ended up using gh-pages to serve rocon_interactions javascript libraries. That seems to be a good low maintenance solution.

**Comment by jihoonl** [comment]
I don't know how we ended up with this style guide. 
You can query this on robot-web-tools@googlegroups.com mailing list to get detailed info.

**Comment by stonier** [comment]
Chad mentioned that was posted by Russel, but not sure where it came from either. He also mentioned that given the variety of javascripting out there, there isn't really a definitive style like there is pep8 for python.
