### ISSUE TITLE
Resource name of interaction icon cannot use absolute system path

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#135]
Only works with ROS packages for me. The [documentation](http://docs.ros.org/indigo/api/rocon_interactions/html/specification.html) also states only a "ROS resource name".

**Comment by stonier** [comment]
huh, that's interesting. I hadn't noticed I'd been doing absolutes over in rapp land, but never in interactions land until now.

**Comment by stonier** [comment]
Patched in 836043afcb.
