### ISSUE TITLE
inheritance of rocon uri

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#19]
I wondered if there is a way of inherit rocon uri.  `waiterbot` is compatible with `turtlebot` rapps.

For example, `waiterbot` is built on top of `turtlebot2` and `kobuki`. It means `waiterbot` should be compatible with `turtlebot`, `turtlebot2`, `kobuki` rapps as well as `waiterbot` rapps.

**Comment by jihoonl** [comment]
It is possible by specifying waiterbot compatibility as `rocon://kobuki|turtlebot|turtlebot2|waiterbot`. But it should be simpler..

**Comment by stonier** [comment]
Jack and I talked about regular expressions, which would let you do things like `turtlebot[0-9]+`. But that is potentially dangerous as it makes it compatible for all future versions too which is likely to cause problems later.

I suspect this is one of those things you can make simple in one place, but it will create problems somewhere else. e.g. inheritance - simpler compatibility strings, but insane `rules.yaml` file.

Anyway, a way to do it exists as you found. It isn't too bad - let's take it for a road test for a while.

**Comment by stonier** [comment]
Closing as we probably won't invest in this. Reopen it if lightning strikes.
