### ISSUE TITLE
rocon_uri cannot parse OR'd names

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#25]
I tried to assign the role if client name is either `kobuki` or `chopin` .
Is this invalid usecase?

```
jihoonl@whoola:~$ rocon_uri parse rocon:/pc/kobuki|chopin#cafe_rapps/waiter
bash: chopin#cafe_rapps/waiter: No such file or directory
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by bit-pirate** [comment]
Isn't Chopin just a robot name, not a type? So, the platform part of the URI should be `kobuki|waiterbot`.

**Comment by stonier** [comment]
See the [specs](http://docs.ros.org/indigo/api/rocon_uri/html/specification.html#special-operations) on this. The OR operator is not valid for the name field, but python regex patterns _should_ work there. I am not sure I made unit tests for that though, so raise another issue if that really is a problem.

**Comment by jihoonl** [comment]
The [specs](http://docs.ros.org/indigo/api/rocon_uri/html/specification.html#special-operations) indicates that Or operator can be used in the `name` field. Shall we fix this?

**Comment by stonier** [comment]
Oh, yes....not meant to be there. I even misread this on providing that link to you again!
