### ISSUE TITLE
Redis client is hanging

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tools#3]
Jihoon thinks this patch to the official redis-py project will fix the hanging:
- https://github.com/andymccurdy/redis-py/pull/256

This created a different error though.

Also made a pull request with jihoon's patch:
- https://github.com/andymccurdy/redis-py/pull/284

Patched redis went in originally in rocon_multimaster: https://github.com/robotics-in-concert/rocon_multimaster/commit/5f01793691c55df7ec38979ca74960ee7959f6d8. It has now been transferred to this repo.

**Comment by stonier** [comment]
If this ever gets fixed, pull our local version out and use that.

**Comment by stonier** [comment]
This is actually ready to have a look at sometime...

**Comment by jihoonl** [comment]
Is this still valid issue?

**Comment by stonier** [comment]
While we are maintaining a patched redis, yes. I never got a chance to test the changes in redis. That needs to happen and if ok, we drop our own redis and close this issue.

**Comment by stonier** [comment]
Closing this - our internal version is working for us. Open a new issue when and where we need a new redis.
