### ISSUE TITLE
[Interactions] Timeout for finding the rapp manager to small

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#37]
When loading multiple rapps the the rapp manager takes a few seconds to get fully ready. During this time it will not advertise its start/stop rapp services, what leads to the interaction manager timing out when looking for those services.

Need to increase the timeout or find a smarter solution to handle this.

**Comment by stonier** [comment]
I just put the search in a background thread. It will bleed heavily now if it fails to find it when asked, and will also cowardly refuse to start paired interactions when not yet initialised.
