### ISSUE TITLE
[Interactions] Cannot stop rapp in pairing mode

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#38]
I get the below error message when stopping the pairing interaction.

```
[ERROR] [WallTime: 1399111872.794629] Interactions : failed to stop a paired rapp [rapp manager's location not known]
```

This happens for both the Qt listener and my implemented teleop interaction/rapp.

**Comment by stonier** [comment]
I was initialising the variable `self.initialised` to `False` after the discovery thread was started and subsequently discovering and then undiscovering the rapp handler.

Reopen if you still have problems.
