### ISSUE TITLE
add 'kobuki' to hardware_platform

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#4]
```
rocon_uri.exceptions.RoconURIValueError: hardware_platform specification is invalid [kobuki]
```

kobuki should be valid!

**Comment by stonier** [comment]
The rocon uri module has a yaml which represents the ebnf rules used to validate rocon uri's. Add kobuki to that list.

https://github.com/robotics-in-concert/rocon_tools/blob/hydro-devel/rocon_uri/yaml/rules.yaml

**Comment by stonier** [comment]
Added in d2344d8da17d0829ac76a1feec76a269f46e8f0a
