### ISSUE TITLE
[Interactions] Better handling of strange error

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#40]
I have seen the following error a couple of times now. It occurs usually when starting a paring interaction.

```
[debug] Remocon : starting interaction [turlebot_teleop/keyboard_teleop.launch]
[debug] InteractiveClient : pairing status callback [rocon_apps/teleop][rqt_remocon_a2dd0170b4dd4e7b9f80bcc7b7ee010d]
[debug] InteractiveClient : interaction request granted
[debug] InteractiveClient : _start_global_executable_interaction [%s]
[remocon_info] publish remocon status
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/rocon_workspace/src/rocon_tools/rocon_python_utils/src/rocon_python_utils/system/popen.py", line 89, in _run_in_thread
    self._proc = subprocess.Popen(popen_args, shell=self._shell, preexec_fn=preexec_fn, env=self._env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

So far, it usually disappeared at some point. I guess, something was misconfigured. In my current case I still have to figure out what's causing this. For doing so, it would be great, if this exception could be caught and appended with some information about what file or directory that program is actually looking for. This would ease the debugging process.

**Comment by bit-pirate** [comment]
After fixing the console output in the remocon (see https://github.com/robotics-in-concert/rocon_qt_gui/pull/107) I know a bit better what's going wrong.

```
[debug] InteractiveClient : pairing status callback [][]
[debug] InteractiveClient : call result
[debug] Remocon : disabling stop interactions button [TurtleBot Keyop]
[debug] Remocon : starting interaction [turlebot_teleop/keyboard_teleop.launch]
[debug] InteractiveClient : pairing status callback [rocon_apps/teleop][rqt_remocon_14c7f9bb27f54c34bf61937961c8df42]
[debug] InteractiveClient : interaction request granted
[debug] InteractiveClient : _start_global_executable_interaction [turlebot_teleop/keyboard_teleop.launch]
[remocon_info] publish remocon status
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/rocon_workspace/src/rocon_tools/rocon_python_utils/src/rocon_python_utils/system/popen.py", line 89, in _run_in_thread
    self._proc = subprocess.Popen(popen_args, shell=self._shell, preexec_fn=preexec_fn, env=self._env)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Looks like the specified launcher is not found and hence treated as a global script. Then the shown exception is raised, when trying to start a roslauncher as a normal process.

So, I can see a couple of issues:
- `rocon_remocon.interactive_client._determine_interaction_type` does not identify unknown interactions, i.e. not a roslauncher, not a rosrunner, not a global script. If this happens, it's most likely the given interactions has been misspelled or is just not locatable
- `rocon_remocon.interactive_client._determine_interaction_type` should throw an error, if a resource with `.launch` extension is provided, but cannot be found.
- There needs to be a way to catch problems when attempting to start a thread via `rocon_python_tools.popen`. I was unable to catch the above exception anywhere outside of `rocon_python_tools.popen._run_in_thread`. This is an problem for the remocon, since it doesn't know, if starting the global script in a separate thread actually worked.

I'll open up issues over in the remocon repo for the related problems. Not sure, if I should open up other issues related to packages within the rocon_tools repo.

**Comment by bit-pirate** [comment]
PS: I got into this whole mess, because I misspelled turtlebot ... `[turlebot_teleop/keyboard_teleop.launch]` ... :tired_face:

**Comment by stonier** [comment]
> There needs to be a way to catch problems when attempting to start a thread via `rocon_python_tools.popen`. I was unable to catch the above exception anywhere outside of `rocon_python_tools.popen._run_in_thread`. 

You can only catch exceptions from _inside_ a process's own universe, not from a parallel universe (that would be an almighty power).

Possibly I could redirect stderr though.

**Comment by stonier** [comment]
https://github.com/robotics-in-concert/rocon_qt_gui/commit/6ced707154573d726c034caaa257f87d0eaf008c - rocon_remocon now provides a popup with an error message if the interaction name ends with `.launch`, but isn't found on the filesystem.

**Comment by stonier** [comment]
https://github.com/robotics-in-concert/rocon_qt_gui/commit/7b18bd5a77ee0d8867be18482d271945de1e00dd - also popup with the error when a rosrunnable/global executable isn't found.
