### ISSUE TITLE
rocon_python_wifi has invalid maintainer and is failing to build

### ISSUE THREAD

**Issue by tfoote** [robotics-in-concert/rocon_tools#41]
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-rocon-python-wifi_binarydeb_saucy_i386/7/console

And without the valid email address it's not notifying anyone useful.

**Comment by stonier** [comment]
Fixed install rule and updated the maintainer - c077288ad87ba69fed1928e3250989ec50213ca0

Thanks Tully.
