### ISSUE TITLE
Create standard set of interactions

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_tools#46]
I propose to create a set of commonly usable interactions, similar to our `rocon_apps`. Example candidates could be _Master Info_ and _Teleop_.

**Comment by stonier** [comment]
I've thought about this for a while, but not sure the extra effort is worth the return. Certainly (at this point) wouldn't be worth replicating the whole inheritable nature as the return value is not there (interactions would just be saving some copy/pasting, while rapps are valuable in the way they abstract a robot and get used in scheduling). 

We could create a library of interactions in `rocon_interactions` that could be linked to by others though. For this to be useful, we'd need to support including interactions files from other files (e.g. [admin.interactions](https://github.com/robotics-in-concert/concert_services/blob/hydro-devel/concert_service_admin/services/admin/admin.interactions) should include a `rocon_interactions/master_info.interactions`.

Ha...I can already see you complaining about the extra lookup time with this scheme ;)

**Comment by bit-pirate** [comment]
Hm, I actually thought this to be much simpler: just create a package containing a few interaction files and include them in the launch files of the rapp manager.

Having a framework in place, which allows sharing, inheritance etc. would be awesome, but I agree with you that the return of this would probably not be worth the effort. Hence, I would only consider a simple implementation like to one proposed above.

> For this to be useful, we'd need to support including interactions files from other files

Why is that required? The parameter in the launcher already allows the inclusion of multiple interaction files: https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_app_manager/launch/includes/_interactions.xml#L6

> Ha...I can already see you complaining about the extra lookup time with this scheme ;)

Yes. I would! :love_hotel:

**Comment by stonier** [comment]
Not going to get this into rocon1. I like being able to customise/brand them anyway :neckbeard:
