### ISSUE TITLE
global name 'MultipleFoundException' is not defined

### ISSUE THREAD

**Issue by asmodehn** [robotics-in-concert/rocon_tools#97]
I encounter this error sometimes:

```
  File "/home/alexv/ROS/gopher_concert/src/rocon_tools/rocon_python_comms/src/rocon_python_comms/namespace.py", line 66, in find_service_namespace
    raise MultipleFoundException(str(found_namespaces))
NameError: global name 'MultipleFoundException' is not defined
```

I m using :
`rocon_tools             git  gopher        c2dc3684237e github.com/robotics-in-concert/rocon_tools.git`

I didnt investigate more than this yet...

**Comment by jihoonl** [comment]
@asmodehn FYI. It has been patched in develop branch and will be released soon.
